name: CI
on:
    push:
        branches:
            - "*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: guardian/actions-setup-node
            - name: build
              run: |
                  yarn
                  yarn validate
                  yarn ci:build
